// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in member's Social Factory profile.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, membership_type, country, city, bio, open_to_connect, onboarded").eq("user_id", ctx.getUserId()).maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? {}) }],
      structuredContent: { profile: data ?? null }
    };
  }
});

// src/lib/mcp/tools/list-noticeboard-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_noticeboard_posts_default = defineTool2({
  name: "list_noticeboard_posts",
  title: "List noticeboard posts",
  description: "List recent noticeboard posts visible to the signed-in member.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many posts to return."),
    category: z.string().trim().min(1).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("noticeboard_posts").select("id, title, body, category, is_pinned, chapter_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-noticeboard-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_noticeboard_post_default = defineTool3({
  name: "create_noticeboard_post",
  title: "Create noticeboard post",
  description: "Publish a new global noticeboard post as the signed-in member.",
  inputSchema: {
    title: z2.string().trim().min(3).max(150).describe("Post title."),
    body: z2.string().trim().min(1).max(5e3).describe("Post body text."),
    category: z2.string().trim().min(1).max(50).optional().describe("Optional category.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, body, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("noticeboard_posts").insert({ author_id: ctx.getUserId(), title, body, category: category ?? "general" }).select("id, title, category, created_at");
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}) }],
      structuredContent: { post: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-proposals.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_proposals_default = defineTool4({
  name: "list_proposals",
  title: "List governance proposals",
  description: "List Social Factory democracy proposals visible to the signed-in member.",
  inputSchema: {
    status: z3.enum(["draft", "open", "closed", "passed", "rejected"]).optional().describe("Optional status filter."),
    limit: z3.number().int().min(1).max(50).default(10).describe("How many proposals to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("proposals").select("id, title, body, type, status, voting_ends_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { proposals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/vote-on-proposal.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var vote_on_proposal_default = defineTool5({
  name: "vote_on_proposal",
  title: "Vote on a proposal",
  description: "Cast or update the signed-in member's vote on a governance proposal.",
  inputSchema: {
    proposal_id: z4.string().uuid().describe("The proposal's id."),
    vote: z4.enum(["yes", "no", "abstain"]).describe("The vote to cast.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ proposal_id, vote }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("proposal_votes").upsert(
      { proposal_id, user_id: ctx.getUserId(), vote },
      { onConflict: "proposal_id,user_id" }
    ).select("proposal_id, vote, created_at");
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? {}) }],
      structuredContent: { vote: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "otquoxstcixxdfmpjkms";
var mcp_default = defineMcp({
  name: "social-factory-ire",
  title: "social-factory-ire",
  version: "0.1.0",
  instructions: "Tools for Social Factory. Read the signed-in member's profile, browse and publish noticeboard posts, and read or vote on governance proposals. All tools act as the authenticated member.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_noticeboard_posts_default, create_noticeboard_post_default, list_proposals_default, vote_on_proposal_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
